-- profiles terhubung ke auth.users
create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text,
  full_name text,
  role text not null default 'user',
  created_at timestamp with time zone not null default now(),
  constraint profiles_pkey primary key (id)
) ;

-- kategori / struktur direktori
create table if not exists public.categories (
  id uuid not null default gen_random_uuid(),
  name text not null,
  parent_id uuid references public.categories(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (id)
) ;

-- dokumen arsip
create table if not exists public.documents (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  letter_number text,
  subject text,
  perihal text,
  letter_date date,
  file_name text,
  file_path text,
  file_size bigint,
  mime_type text,
  status text not null default 'DRAFT',
  uploaded_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint documents_pkey primary key (id)
) ;

-- audit log aktivitas
create table if not exists public.audit_logs (
  id bigint generated by default as identity,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  document_id uuid references public.documents(id) on delete set null,
  metadata jsonb,
  created_at timestamp with time zone not null default now(),
  constraint audit_logs_pkey primary key (id)
) ;

-- index untuk performa query
create index if not exists idx_documents_user_id on public.documents(user_id);
create index if not exists idx_documents_category_id on public.documents(category_id);
create index if not exists idx_audit_logs_user_id on public.audit_logs(user_id);

-- RLS
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.documents enable row level security;
alter table public.audit_logs enable row level security;

-- policies
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can view own profile') then
    create policy "Users can view own profile"
      on public.profiles for select
      using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile"
      on public.profiles for update
      using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'categories' and policyname = 'Categories readable by authenticated users') then
    create policy "Categories readable by authenticated users"
      on public.categories for select
      to authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Documents readable by owner') then
    create policy "Documents readable by owner"
      on public.documents for select
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Documents insertable by authenticated users') then
    create policy "Documents insertable by authenticated users"
      on public.documents for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Documents updateable by owner') then
    create policy "Documents updateable by owner"
      on public.documents for update
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Documents deletable by owner') then
    create policy "Documents deletable by owner"
      on public.documents for delete
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'audit_logs' and policyname = 'Audit logs readable by owner') then
    create policy "Audit logs readable by owner"
      on public.audit_logs for select
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'audit_logs' and policyname = 'Audit logs insertable by system') then
    create policy "Audit logs insertable by system"
      on public.audit_logs for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

-- trigger untuk created_by / updated_by
drop trigger if exists on_auth_user_created on auth.users;

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- storage bucket untuk dokumen arsip
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

-- RLS storage: pemilik bisa mengelola file di folder userId-nya
create policy "Documents storage readable by owner"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Documents storage insertable by owner"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Documents storage updateable by owner"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Documents storage deletable by owner"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

